name: Autograding Tests
on:
  push:
  workflow_dispatch:
  repository_dispatch:
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Cobertura de Código
      id: cobertura
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Cobertura de Código
        setup-command: ''
        command: cd sgcmapi && mvn clean test jacoco:check
        timeout: 15
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        COBERTURA_RESULTS: "${{steps.cobertura.outputs.result}}"
      with:
        runners: cobertura
